SELECT TOP (100)
    [City Key]
      , [WWI City ID]
      , [City]
      , [State Province]
      , [Sales Territory]
      , [Region]
      , [Subregion]
      , [Location]
      , [Latest Recorded Population]
      , [Valid From]
      , [Valid To]
      , [Lineage Key]
FROM [WideWorldImportersDW].[Dimension].[City]